### ISSUE TITLE
Detroid jar-file of the chess engine and GUI

### ISSUE THREAD

**Issue by ChessGUI** [ViktorC/DETROID#1]
Can you build a platform-independent jar-file of the the chess engine and GUI?

Some graphical user interfaces like Arena, ChessGUI or WinBoard support Java executables.

http://www.oracle.com/technetwork/java/javase/downloads/jre8-downloads-2133155.html

Your website is no longer available and seems to be free now.

**Comment by ViktorC** [comment]
The latest build can be found in the target folder. You can download it from [here](https://github.com/ViktorC/DETROID/blob/master/DETROID/target/detroid-1.0.jar).

Edit: By default, it runs in GUI mode (which means that it uses its own GUI). To use it with the user interfaces you mentioned, you have to run it in UCI mode. You can do that by starting it with the `-u` parameter. In Arena, you can specify this in the "Command Line Parameters" field of the engine's management page. I am not sure if the other GUIs support this as well, but on Windows, for example, you can create a batch file containing the command `java -jar "detroid-1.0.jar" -u` (assuming that the engine is in the same folder) and simply import this .bat file as the engine in any GUI.
